
package es.nimio.nimiogcs.servicios.externos.sw.deployer;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "ServicePAI", targetNamespace = "http://ws.nimio.es", wsdlLocation = "http://localhost:8160/services/ServicePAI?wsdl")
public class ServicePAI
    extends Service
{

    private final static URL SERVICEPAI_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(es.nimio.nimiogcs.servicios.externos.sw.deployer.ServicePAI.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = es.nimio.nimiogcs.servicios.externos.sw.deployer.ServicePAI.class.getResource(".");
            url = new URL(baseUrl, "http://localhost:8160/services/ServicePAI?wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'http://localhost:8160/services/ServicePAI?wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        SERVICEPAI_WSDL_LOCATION = url;
    }

    public ServicePAI(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }
    
    public ServicePAI(URL wsdlLocation) {
    	super(wsdlLocation, new QName("http://ws.nimio.es", "ServicePAI"));
    }

    private ServicePAI() {
        super(SERVICEPAI_WSDL_LOCATION, new QName("http://ws.nimio.es", "ServicePAI"));
    }

    /**
     * 
     * @return
     *     returns ServicePAIPortType
     */
    @WebEndpoint(name = "ServicePAIHttpSoap11Endpoint")
    public ServicePAIPortType getServicePAIHttpSoap11Endpoint() {
        return super.getPort(new QName("http://ws.nimio.es", "ServicePAIHttpSoap11Endpoint"), ServicePAIPortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ServicePAIPortType
     */
    @WebEndpoint(name = "ServicePAIHttpSoap11Endpoint")
    public ServicePAIPortType getServicePAIHttpSoap11Endpoint(WebServiceFeature... features) {
        return super.getPort(new QName("http://ws.nimio.es", "ServicePAIHttpSoap11Endpoint"), ServicePAIPortType.class, features);
    }

    /**
     * 
     * @return
     *     returns ServicePAIPortType
     */
    @WebEndpoint(name = "ServicePAIHttpSoap12Endpoint")
    public ServicePAIPortType getServicePAIHttpSoap12Endpoint() {
        return super.getPort(new QName("http://ws.nimio.es", "ServicePAIHttpSoap12Endpoint"), ServicePAIPortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ServicePAIPortType
     */
    @WebEndpoint(name = "ServicePAIHttpSoap12Endpoint")
    public ServicePAIPortType getServicePAIHttpSoap12Endpoint(WebServiceFeature... features) {
        return super.getPort(new QName("http://ws.nimio.es", "ServicePAIHttpSoap12Endpoint"), ServicePAIPortType.class, features);
    }

    /**
     * 
     * @return
     *     returns ServicePAIPortType
     */
    @WebEndpoint(name = "ServicePAIHttpEndpoint")
    public ServicePAIPortType getServicePAIHttpEndpoint() {
        return super.getPort(new QName("http://ws.nimio.es", "ServicePAIHttpEndpoint"), ServicePAIPortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ServicePAIPortType
     */
    @WebEndpoint(name = "ServicePAIHttpEndpoint")
    public ServicePAIPortType getServicePAIHttpEndpoint(WebServiceFeature... features) {
        return super.getPort(new QName("http://ws.nimio.es", "ServicePAIHttpEndpoint"), ServicePAIPortType.class, features);
    }

}
